# No Import

# TASKS TRIGGERS
TASK_TRIGGER_EVENT = 0
TASK_TRIGGER_TIME = 1
TASK_TRIGGER_DAILY = 2
TASK_TRIGGER_WEEKLY = 3
TASK_TRIGGER_MONTHLY = 4
TASK_TRIGGER_MONTHLYDOW = 5
TASK_TRIGGER_IDLE = 6
TASK_TRIGGER_REGISTRATION = 7
TASK_TRIGGER_BOOT = 8
TASK_TRIGGER_LOGON = 9
TASK_TRIGGER_SESSION_STATE_CHANGE = 11
TASK_TRIGGER_CUSTOM_TRIGGER_01 = 12

# DAYS
DAY_SUNDAY = 1
DAY_MONDAY = 2
DAY_TUESDAY = 4
DAY_WEDNESDAY = 8
DAY_THURSDAY = 16
DAY_FRIDAY = 32
DAY_SATURDAY = 64
ALL_DAYS = (DAY_SUNDAY | DAY_MONDAY | DAY_TUESDAY | DAY_WEDNESDAY | DAY_THURSDAY | DAY_FRIDAY | DAY_SATURDAY)

# MONTHS
MONTH_JANUARY = 1
MONTH_FEBRUARY = 2
MONTH_MARCH = 4
MONTH_APRIL = 8
MONTH_MAY = 16
MONTH_JUNE = 32
MONTH_JULY = 64
MONTH_AUGUST = 128
MONTH_SEPTEMBER = 256
MONTH_OCTOBER = 512
MONTH_NOVEMBER = 1024
MONTH_DECEMBER = 2048
ALL_MONTHS = (MONTH_JANUARY | MONTH_FEBRUARY | MONTH_MARCH | MONTH_APRIL | MONTH_MAY | MONTH_JUNE | MONTH_JULY |
              MONTH_AUGUST | MONTH_SEPTEMBER | MONTH_OCTOBER | MONTH_NOVEMBER | MONTH_DECEMBER)  # = 4095

# TASKS ACTIONS
TASK_ACTION_EXEC = 0
TASK_ACTION_COM_HANDLER = 5
TASK_ACTION_SEND_EMAIL = 6
TASK_ACTION_SHOW_MESSAGE = 7

# TASKS CREATION TYPES
TASK_VALIDATE_ONLY = 1
TASK_CREATE = 2
TASK_UPDATE = 4
TASK_CREATE_OR_UPDATE = TASK_CREATE | TASK_UPDATE  # = 6
TASK_DISABLE = 8
TASK_DONT_ADD_PRINCIPAL_ACE = 16
TASK_IGNORE_REGISTRATION_TRIGGERS = 32

# TASKS LOGON TYPES
TASK_LOGON_NONE = 0
TASK_LOGON_PASSWORD = 1
TASK_LOGON_S4U = 2
TASK_LOGON_INTERACTIVE_TOKEN = 3
TASK_LOGON_GROUP = 4
TASK_LOGON_SERVICE_ACCOUNT = 5
TASK_LOGON_INTERACTIVE_TOKEN_OR_PASSWORD = 6
